runtime: python
env: flex
entrypoint: gunicorn -b :8080 -w 2 --timeout 120 main:app
service: flex-proverbs

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10